version: '2'

services:
  myapp:
    image: docker.io/bitnami/symfony:1
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    environment:
      - AWS_ACCESS_KEY_ID=...
      - AWS_SECRET_ACCESS_KEY=...
      - AWS_DEFAULT_REGION=us-west-2
    depends_on:
      - mariadb
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
